[package]
name = "mini-json-parser"
version = "0.1.0"
authors = ["Sang-Heon Jeon <ekffu200098@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty_assertions = "0.6.1"
